language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: deployment-jcho42
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: vYmmrh6owC6dY2Z2rx39Ex/MjsZmTu5tnCHB+EYedciFozPaISNpGdigIOPJ/hOvNlDOMfMGdKI0IjoEr8JqNaFhJDgiEDCKfwENx6hqhvuBpOv5wKQktLN8oXwbyd2wCCLqFxXleuqNNZKKbgmtIl8/MT2UErlTaRO3GFFavmaUQBzViyvP1GWyLt9sv/5R006SkViaIrf9W23xPBtOCvBGFTU0dlabrvykGk3EE5pg5gnuF9r/mTq2g8JS8EQd4yTRuqz5GnWcS0SHCD+jEB5iLUIQg1neYZGeW83G1/RQULwihD3FsslTx9jgIsJzARn24KKKoVSUD7MW9lTIDS1MtbE9UIrKzbeco51i9k65wHcgQcumWZs5TSfuQo8pGiSkgZeUMK1DQHLH/0gwn8nEuCs6yUJRngm74s6AUlhmO5vXS/sY0UKa5PlNJc+BJDXbeGfLr18V60093xdmlCTTLRy7cQj8qHHR8RODlLE0gqnNMBblg4qB9dd0KQ7atj7mzK+Rucjy5hUXFoJ0TsdRh+QK6L79mxoDAQxl7f7UPs4PNRiZaUB/kem73h2iPynAHZhAPB7BrtX2EVn5yZ/NTp9traTtPr2c86j0JNWs00LnTn8+tGRyVmq3Cx3+sw2ydpklU2iIGWGVdt8yJibMGc/E/BFPnoQhZwi4k40=
